version: '3'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: offerdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5438:5432'
    volumes:
      - ./init:/docker-entrypoint-initdb.d